import { CSSProperties } from "react";

// Define styles here for inline application
const bubbleStyles: Record<string, CSSProperties> = {
  bubble: {
    width: "60px",
    height: "60px",
    backgroundColor: "transparent",
    color: "white",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "28px",
    fontWeight: "bold",
    cursor: "grab",
    userSelect: "none",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
    border: "3px solid white",
    transition: "transform 0.2s ease-out",
    position: "relative",
    overflow: "hidden",
  },
  bubbleImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "50%",
  },
  chatbox: {
    width: "320px",
    height: "450px",
    backgroundColor: "white",
    border: "1px solid #e0e0e0",
    borderRadius: "12px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.15)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    cursor: "default",
    position: "absolute",
    transformOrigin: "bottom right",
    animation: "fadeIn 0.2s ease-out",
    // Position will be dynamically calculated
  },
  chatboxHeader: {
    backgroundColor: "#f8f9fa",
    padding: "14px 16px",
    borderBottom: "1px solid #e0e0e0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: "12px 12px 0 0",
  },
  chatboxContent: {
    padding: "15px",
    flexGrow: 1,
    overflowY: "auto" as const,
  },
  chatboxFooter: {
    padding: "12px 15px",
    borderTop: "1px solid #e6e6e6",
    backgroundColor: "#f8f9fa",
    borderRadius: "0 0 12px 12px",
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    gap: "10px",
  },
  chatInput: {
    width: "100%",
    border: "1px solid #e0e0e0",
    borderRadius: "20px",
    padding: "10px 15px",
    fontFamily: "inherit",
    fontSize: "14px",
    outline: "none",
    resize: "none" as const,
    flexGrow: 1,
    backgroundColor: "white",
    minHeight: "40px",
  },
  sendButton: {
    backgroundColor: "#ff4500",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: "bold",
    transition: "background-color 0.2s ease",
    flexShrink: 0,
  },
  sendArrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  closeButton: {
    background: "none",
    border: "none",
    fontSize: "24px",
    cursor: "pointer",
    color: "#666",
    padding: "2px 5px",
    lineHeight: 1,
    transition: "color 0.2s ease",
  },
  chatMessage: {
    margin: "10px 0",
    padding: "8px 12px",
    borderRadius: "18px",
    maxWidth: "80%",
    wordBreak: "break-word",
    position: "relative",
  },
  userMessage: {
    backgroundColor: "#0088ff",
    color: "white",
    alignSelf: "flex-end",
    marginLeft: "auto",
    borderTopRightRadius: "4px",
  },
  botMessage: {
    backgroundColor: "#f0f0f0",
    color: "#333",
    alignSelf: "flex-start",
    borderTopLeftRadius: "4px",
  },
  messagesContainer: {
    display: "flex",
    flexDirection: "column-reverse" as const,
    padding: "15px",
    overflowY: "auto" as const,
    flexGrow: 1,
    scrollBehavior: "smooth" as const,
    gap: "8px",
  },
  messageTimeGroup: {
    display: "flex",
    flexDirection: "column" as const,
    marginBottom: "10px",
  },
  messageWrapper: {
    display: "flex",
    gap: "8px",
    alignItems: "flex-start",
  },
  conversationHeader: {
    backgroundColor: "#f8f9fa",
    padding: "14px 16px",
    borderBottom: "1px solid #e0e0e0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "grab",
    borderRadius: "12px 12px 0 0",
  },
  conversationTitleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  conversationAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    objectFit: "cover",
  },
  conversationTitle: {
    fontWeight: "bold",
    fontSize: "16px",
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  conversationClose: {
    background: "none",
    border: "none",
    fontSize: "18px",
    cursor: "pointer",
    color: "#666",
    padding: "8px",
    lineHeight: "1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerInfo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  headerAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    objectFit: "cover" as const,
  },
  headerText: {
    display: "flex",
    flexDirection: "column" as const,
  },
  headerName: {
    fontWeight: "bold",
    fontSize: "16px",
  },
  emptyState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    color: "#888",
    fontSize: "14px",
  },
  userMessageWrapper: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse" as const,
  },
  messageAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    objectFit: "cover" as const,
  },
  messageContent: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1px",
  },
  messageSender: {
    fontSize: "12px",
    fontWeight: "bold",
    color: "#666",
    marginBottom: "2px",
    paddingLeft: "4px",
  },
  messageText: {
    padding: "8px 12px",
    borderRadius: "12px",
    fontSize: "14px",
    lineHeight: "1.4",
    wordBreak: "break-word" as const,
  },
  userMessageText: {
    backgroundColor: "#e1f5fe",
    color: "#333",
    borderRadius: "12px 12px 2px 12px",
  },
  botMessageText: {
    backgroundColor: "#f5f5f5",
    color: "#333",
    borderRadius: "12px 12px 12px 2px",
  },
  messageTime: {
    fontSize: "11px",
    color: "#888",
    marginTop: "2px",
    alignSelf: "flex-end",
    marginBottom: "2px",
  },
  headerStatus: {
    fontSize: "12px",
    color: "#888",
    display: "none", // Hide the status
  },
  dateContainer: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    margin: "8px 0",
  },
  dateLabel: {
    fontSize: "12px",
    color: "#888",
    backgroundColor: "#f0f2f5",
    padding: "2px 8px",
    borderRadius: "10px",
    display: "inline-block",
  },
  sameTimeMessages: {
    marginBottom: "2px",
  },
  differentTimeMessages: {
    marginBottom: "8px",
  },
  messageBadge: {
    position: "absolute",
    top: "0",
    right: "0",
    backgroundColor: "#0088ff",
    color: "white",
    borderRadius: "50%",
    width: "22px",
    height: "22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: "bold",
    border: "2px solid white",
    boxShadow: "0 2px 5px rgba(0, 0, 0, 0.2)",
    transform: "translate(30%, -30%)",
    zIndex: 10,
  },
};

export default bubbleStyles;
